knp_paginator:
    page_range: 5                      
    page_limit: 1000                    
    convert_exception: false           
    default_options:
        page_name: page                
        sort_field_name: sort          
        sort_direction_name: direction 
        distinct: true                 
        page_out_of_range: ignore      
        default_limit: 15              
        filter_field_name: filterField  
        filter_value_name: filterValue  
        
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'    
        sortable: '@KnpPaginator/Pagination/bootstrap_v5_fa_sortable_link.html.twig'     
        filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'
